// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "get homepage",
                "tags": [
                    "medidores"
                ],
                "summary": "homepage",
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/medidores": {
            "get": {
                "description": "get medidores",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medidores"
                ],
                "summary": "Show all medidores",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/models.Medidor"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "crea un medidor en la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medidores"
                ],
                "summary": "crea un medidor en la base de datos",
                "parameters": [
                    {
                        "description": "crea un nuevo medidor",
                        "name": "medidor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Medidor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Medidor"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/medidores/active/{is_Active}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "medidor eliminado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/medidores/search/{brand}/{serial}": {
            "get": {
                "responses": {
                    "200": {
                        "description": "medidor eliminado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/medidores/{id}": {
            "get": {
                "description": "get medidor por id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medidores"
                ],
                "summary": "Show an medidor",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "medidor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Medidor"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "description": "actualiza un medidor en la base de datos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medidores"
                ],
                "summary": "actualiza un medidor en la base de datos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "medidor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "actualiza un nuevo medidor, los campos como brand, serial, id, createdAt, no son editables",
                        "name": "medidor",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/models.Medidor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Medidor"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "description": "elimina un medidor en la base de datos por su id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "medidores"
                ],
                "summary": "elimina un medidor en la base de datos por su id",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "medidor ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "medidor eliminado",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Medidor": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "brand": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "installation_date": {
                    "type": "string",
                    "example": "0000-12-31T19:00:00-05:00"
                },
                "is_active": {
                    "type": "boolean"
                },
                "lines": {
                    "type": "integer"
                },
                "retirement_date": {
                    "type": "string",
                    "example": "0000-12-31T19:00:00-05:00"
                },
                "serial": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.1",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Medidores de Energia",
	Description:      "Esta api se encarga de llevar el control de los medidores de energia de la empresa enerBit, donde se presenta el reto de registrar y hacer seguimiento de los medidores de energía que se han instalado en los predios de nuestros clientes,  para efectos de pruebas en modo local se manejara la url localhost:3000, recuerde primero inicialiar la base de datos, tal como se solicito en la prueba tecnica, se realizo un container en docker el cual tiene la base de datos, los archivos de ejemplo para la conexion a la base de datos se especifican en el archivo env.example, estos deben guardarse como variables de entorno. para mas info consultar archivo readme.md",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
